### ISSUE TITLE
Undefined method in ical_filter_proxy.rb

### ISSUE THREAD

**Issue by InterLinked1** [darkphnx/ical-filter-proxy#16]
I tried installing and running this program, but I'm getting a crash due to an undefined method:

```
Traceback (most recent call last):
        22: from /usr/local/bin/rackup:23:in `<main>'
        21: from /usr/local/bin/rackup:23:in `load'
        20: from /var/lib/gems/2.5.0/gems/rack-2.1.4/bin/rackup:5:in `<top (required)>'
        19: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:170:in `start'
        18: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:313:in `start'
        17: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:381:in `handle_profiling'
        16: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:314:in `block in start'
        15: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:424:in `wrapped_app'
        14: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:251:in `app'
        13: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/server.rb:351:in `build_app_and_options_from_config'
        12: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:40:in `parse_file'
        11: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:59:in `load_file'
        10: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `new_from_string'
         9: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:65:in `eval'
         8: from /root/ical-filter-proxy/config.ru:in `<main>'
         7: from /root/ical-filter-proxy/config.ru:in `new'
         6: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `initialize'
         5: from /var/lib/gems/2.5.0/gems/rack-2.1.4/lib/rack/builder.rb:71:in `instance_eval'
         4: from /root/ical-filter-proxy/config.ru:5:in `block in <main>'
         3: from /root/ical-filter-proxy/lib/ical_filter_proxy.rb:16:in `filters'
         2: from /root/ical-filter-proxy/lib/ical_filter_proxy.rb:16:in `each_with_object'
         1: from /root/ical-filter-proxy/lib/ical_filter_proxy.rb:16:in `each'
/root/ical-filter-proxy/lib/ical_filter_proxy.rb:19:in `block in filters': undefined method `each' for nil:NilClass (NoMethodError)
```

I'm running on a Debian 10 server. Here's what I did:

```
 git clone https://github.com/darkphnx/ical-filter-proxy.git
apt-get install gem # I think this was the wrong one
apt-get install rubygems
gem install bundler
bundle update --bundler # bundle install failed and says to run this first
bundle install
bundle exec rackup -p 8000
```

I tried running on different ports, no dice. Here is the (simple) config.yml in use:

```
personal:
   ical_url: https://outlook.live.com/owa/calendar/redacted/calendar.ics # Source calendar
   api_key:  somethinghere # (optional) append ?key=myapikey to your URL to grant access
   rules:
```

I also initially tried it without the `rules:` but that made no difference either way.

I have no Ruby background myself but hopefully this narrows it down - if not, let me know and I can provide more debug.

**Comment by darkphnx** [comment]
You need to define some rules in the config.yml. It's tripping up because it expects an array under rules:, but one isn't present here.

I should be able to add a guard clause there to improve the user experience, but that's your problem.

**Comment by odin568** [comment]
Makes Sense to guard, then it acts simply as a Proxy with optional apiToken
